export enum NotificationType {
  ALL = 'ALL',
  BACKUP_SUCCESS = 'BACKUP_SUCCESS',
  BACKUP_FAILED = 'BACKUP_FAILED',
  HEALTHCHECK_SUCCESS = 'HEALTHCHECK_SUCCESS',
  HEALTHCHECK_FAILED = 'HEALTHCHECK_FAILED',
  VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
}
